//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIS.Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblanalytic
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblanalytic()
        {
            this.tblpatienttestresults = new HashSet<tblpatienttestresult>();
        }
    
        public int analyticid { get; set; }
        public string diagnosisitem { get; set; }
        public Nullable<double> value { get; set; }
        public Nullable<double> minvalue { get; set; }
        public Nullable<double> maxvalue { get; set; }
        public string measurementunit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblpatienttestresult> tblpatienttestresults { get; set; }
    }
}
