//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIS.Model.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblbill
    {
        public int billid { get; set; }
        public Nullable<int> patientid { get; set; }
        public Nullable<double> totalprice { get; set; }

        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]

        public Nullable<System.DateTime> generateddate { get; set; }
        public Nullable<int> recordid { get; set; }
    
        public virtual tblrecord tblrecord { get; set; }
        public virtual tblpatient tblpatient { get; set; }
    }
}
