//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIS.Model.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblrecord
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblrecord()
        {
            this.tblbills = new HashSet<tblbill>();
            this.tblpatienttestresults = new HashSet<tblpatienttestresult>();
        }
    
        public int recordid { get; set; }
        public Nullable<int> patientid { get; set; }
        public Nullable<int> doctorid { get; set; }
        public Nullable<int> collectorid { get; set; }
        public string samplenumber { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> date { get; set; }
        public string testid { get; set; }
        public Nullable<bool> priority { get; set; }
        public Nullable<bool> status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblbill> tblbills { get; set; }
        public virtual tblcollector tblcollector { get; set; }
        public virtual tbldoctor tbldoctor { get; set; }
        public virtual tblpatient tblpatient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblpatienttestresult> tblpatienttestresults { get; set; }

        [NoteMapped]
        public string[] testid_Array { get; set; }

    }
}
